enhancement: new keywords and syntax support
sarvalabs/vscode-coco pull request #3
Opened 2023-08-08 10:53 UTC by sarvalabs-sarthak

# Description
- callable functions are now renamed to endpoints
- 'local' is no longer a function modifier keyword
- 'func' by default now denotes a locally callable function
- 'elif 'support is dropped, 'else if' must be used in conditional statements
- 'join' and 'len' are now special method keywords
- var is now fixed to allow multiple named variables of same type in one line
- version updated to 0.1.1

# Changes include
-  New feature (non-breaking change that adds functionality)

# Checklist

- I have assigned this PR to myself
- I have added at least 1 reviewer
- I have tested this code

2023-08-08 10:59 UTC, sarvalabs-robert approved these changes

2023-08-09 06:20 UTC, sarvalabs-manish requested changes

2023-08-09 06:20 UTC, sarvalabs-manish commented on syntaxes/coco.tmLanguage.json
> +                            "name": "keyword.state.coco"
rename this to `keyword.state.accessor.coco`

2023-08-09 09:18 UTC, sarvalabs-manish approved these changes
LGTM 🚀

2023-08-09 09:19 UTC, merged